name: Trivy IaC Scan (CloudFormation)

on:
  workflow_dispatch:
  push:
    inputs:
      server_ip:
        description: 'Severity'
        required: true
        default: "CRITICAL,HIGH,LOW"
        type: choice
        options:
        - CRITICAL
        - HIGH
        - MEDIUM

jobs:
  trivy-iac-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
    # Build Docker image
      - name: Build Docker image
        run: docker build -t pygoat:latest .

      - name: Run Container Image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: "image"
          scan-ref: "pygoat:latest"
          severity: "CRITICAL,HIGH,MEDIUM"
          format: "table"
          exit-code: "0"
        env:
         TRIVY_SKIP_DB_UPDATE: true
         TRIVY_SKIP_JAVA_DB_UPDATE: true
    